all: 
	jar cf bin/server.jar server/*.java sharedPackages/*.java
	jar cf bin/client.jar client/*.java sharedPackages/*.java
server: 
	jar cf bin/server.jar server/*.java sharedPackages/*.java

client: 
	jar cf bin/client.jar client/*.java sharedPackages/*.java
